import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/about";
import Header from "../components/header";
import Portfolio from "../components/portfolio/index";
import Experience from "../components/experience";
import { introSection } from "../config";

const Home: NextPage = () => (
  <div>
    <Head>
      <title>OpenFolio - Portfolio for everyone.</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      {introSection.display && <Header />}
      <About />
      <Portfolio />
      <Experience />
    </main>

    {/* <footer className={styles.footer}>

    </footer> */}
  </div>
);

export default Home;
