import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>OpenFolio - Portfolio for everyone.</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </main>

    {/* <footer className={styles.footer}>

    </footer> */}
  </div>
);

export default Home;
